import assert from 'node:assert/strict';
import { MultiAccountCopyExecution } from '../src/multi-account-copy-execution.js';
import { RiskEngine } from '../src/risk-engine.js';
import { ExecutionEngine } from '../src/execution-engine.js';

const make = (id, maxExposure = 1000) => ({ accountId: id, riskEngine: new RiskEngine({ maxOrderNotional: 1000, maxDailyLoss: 100, maxExposure }), executionEngine: new ExecutionEngine() });
const test = (name, fn) => { try { fn(); console.log(`PASS: ${name}`); } catch (err) { console.error(`FAIL: ${name}`); throw err; } };
const signal = { signalId: 'sig-1', symbol: 'BTCUSDT', side: 'BUY', quantity: 1, price: 100 };

test('fan-out submits independently to every enabled account', () => { const c = new MultiAccountCopyExecution({ accounts: [make('a'), make('b'), make('c')] }); const r = c.executeCopy(signal); assert.equal(r.submitted, 3); assert.equal(r.results.every(x => x.order.clientOrderId.startsWith('copy:sig-1:')), true); });
test('account risk rejection does not block other accounts', () => { const good = make('good'); const bad = make('bad', 50); const c = new MultiAccountCopyExecution({ accounts: [good, bad] }); const r = c.executeCopy(signal); assert.equal(r.submitted, 1); assert.equal(r.rejected, 1); assert.equal(good.executionEngine.getOrderByClientId('copy:sig-1:good') !== null, true); });
test('one account submission failure is isolated and reservation is released', () => { const good = make('good'); const bad = make('bad'); bad.executionEngine.createOrder = () => { throw new Error('transport failure'); }; const c = new MultiAccountCopyExecution({ accounts: [good, bad] }); const r = c.executeCopy(signal); assert.equal(r.submitted, 1); assert.equal(r.failed, 1); assert.equal(bad.riskEngine.reservedExposure, 0); });
test('duplicate signal is idempotent per account', () => { const c = new MultiAccountCopyExecution({ accounts: [make('a'), make('b')] }); const first = c.executeCopy(signal); const second = c.executeCopy(signal); assert.equal(first.submitted, 2); assert.equal(second.idempotent, 2); assert.equal(second.submitted, 0); assert.equal(c.accounts.get('a').riskEngine.reservedExposure, 100); });
test('same signal id cannot be reused with conflicting order data', () => { const c = new MultiAccountCopyExecution({ accounts: [make('a')] }); c.executeCopy(signal); assert.throws(() => c.executeCopy({ ...signal, quantity: 2 }), /conflicting copy idempotency key/); });
test('disabled account is skipped without consuming risk', () => { const a = make('a'); const c = new MultiAccountCopyExecution({ accounts: [a] }); c.setAccountEnabled('a', false); const r = c.executeCopy(signal); assert.equal(r.skipped, 1); assert.equal(a.riskEngine.reservedExposure, 0); assert.equal(a.executionEngine.getOrderByClientId('copy:sig-1:a'), null); });
test('re-enabling account permits later signal', () => { const c = new MultiAccountCopyExecution({ accounts: [make('a')] }); c.setAccountEnabled('a', false); c.executeCopy(signal); c.setAccountEnabled('a', true); const r = c.executeCopy({ ...signal, signalId: 'sig-2' }); assert.equal(r.submitted, 1); });
test('duplicate client order id cannot double-reserve exposure', () => { const a = make('a'); const c = new MultiAccountCopyExecution({ accounts: [a] }); c.executeCopy(signal); c.executeCopy(signal); assert.equal(a.riskEngine.reservedExposure, 100); assert.equal(a.executionEngine.orders.size, 1); });
test('many accounts remain isolated under mixed outcomes', () => { const accounts = [make('a', 1000), make('b', 50), make('c', 1000), make('d', 1000), make('e', 50)]; accounts[2].executionEngine.createOrder = () => { throw new Error('exchange down'); }; const c = new MultiAccountCopyExecution({ accounts }); const r = c.executeCopy(signal); assert.equal(r.submitted, 2); assert.equal(r.rejected, 2); assert.equal(r.failed, 1); assert.equal(accounts[2].riskEngine.reservedExposure, 0); });
test('risk reservations are released after simulated terminal fill lifecycle', () => { const a = make('a'); const c = new MultiAccountCopyExecution({ accounts: [a] }); const r = c.executeCopy(signal); const id = r.results[0].order.id; assert.equal(a.riskEngine.reservedExposure, 100); a.riskEngine.commitReservedExposure(100); assert.equal(a.riskEngine.reservedExposure, 0); assert.equal(a.riskEngine.exposure, 100); assert.equal(a.executionEngine.onExchangeFill(id, 1, 'fill-1').status, 'FILLED'); });
test('audit records one aggregate result per signal', () => { const c = new MultiAccountCopyExecution({ accounts: [make('a')] }); c.executeCopy(signal); const audit = c.getAuditLog(); assert.equal(audit.at(-1).type, 'COPY_EXECUTED'); assert.equal(audit.at(-1).summary.submitted, 1); });
console.log('Gate 8: ALL TESTS PASSED');
